### ISSUE TITLE
Configure traces filter from the shake detector.

### ISSUE THREAD

**Issue by pedrovgs** [pedrovgs/Lynx#15]
I'm using lynx and it's open automatically if I shake the phone. The problem with this usage is that right now it's impossible to configure the filter we are going to use by default. 

We should be able to pass a LynxConfig instance to the ShakeDetector. This config object will be used to start LynxActivity when the user shakes the phone.

This is the current Lynx usage from any Application class:

```java

public void onCreate(){
    super.onCreate();
    initializeLynx();
}

private void initializeLynx() {
    if (BuildConfig.DEBUG) {
      LynxShakeDetector lynxShakeDetector = new LynxShakeDetector(this);
      lynxShakeDetector.init();
    }
  }

```

This is the proposed configuration:

```java

public void onCreate(){
    super.onCreate();
    initializeLynx();
}

private void initializeLynx() {
    if (BuildConfig.DEBUG) {
      LynxShakeDetector lynxShakeDetector = new LynxShakeDetector(this);
        LynxConfig lynxConfig = new LynxConfig();
        lynxConfig.setMaxNumberOfTracesToShow(4000).setFilter("LynxFilter");
      lynxShakeDetector.init(lynxConfig);
    }
  }

```

**Comment by pedrovgs** [comment]
@manolovn I'm sure you can add this feature in less than two hours of your time ;)

**Comment by vic-gonzi** [comment]
Proposed PR: https://github.com/pedrovgs/Lynx/pull/20 .
