### ISSUE TITLE
Support filter by trace level.

### ISSUE THREAD

**Issue by pedrovgs** [pedrovgs/Lynx#2]
In order to improve the usage of the library could be really cool to support another filter based on the level of the trace: debug, verbose, warning, error...

**Comment by rallat** [comment]
:+1: this is a killer feature

**Comment by pedrovgs** [comment]
It's easy to implemet!!

**Comment by pedrovgs** [comment]
Killer feature implemented by @rallat. I'm going to add a new section in the readme with a list of contributors and you'll be there ;)
